version: '2'
services:
  logfan:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: bitfan
    volumes:
      - ./config:/config
    command: run /config/simple.conf      
